# Generated by Django 3.1.8 on 2021-06-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='collection_id',
            new_name='collection',
        ),
    ]
